### ISSUE TITLE
Could not pass event PlayerExchangeShopEvent to MysqlPlayerDataBridge v3.34.0

### ISSUE THREAD

**Issue by Craftplaza** [snowgears/shopbugs#107]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When a player buy something in a shop. Then the error below came in the console.
When the owner of the shop is offline he don't take the money.  

**Screenshots**

**Version:**
 - Spigot version: [e.g. Spigot 1.16.1]
 - Shop version [e.g. 1.8.1]

**Additional context**
[01:19:00] [Server thread/ERROR]: Could not pass event PlayerExchangeShopEvent to MysqlPlayerDataBridge v3.34.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at com.snowgears.shop.SellShop.executeTransaction(SellShop.java:90) ~[?:?]
	at com.snowgears.shop.listener.TransactionListener.executeTransaction(TransactionListener.java:111) ~[?:?]
	at com.snowgears.shop.listener.TransactionListener.onShopSignClick(TransactionListener.java:98) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:465) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1284) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: com.snowgears.shop.event.PlayerExchangeShopEvent.getShop()Lcom/snowgears/shop/ShopObject;
	at net.craftersland.data.bridge.events.ShopSupport.onShopTransaction(ShopSupport.java:25) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1-1-7.2020.jar:git-Spigot-4d9262c-3b9cf0f]
	... 31 more

**Comment by snowgears** [comment]
Please try shop 1.8.2 on a supported version of Spigot (1.16+) and reopen the ticket if the issue persists.
