### ISSUE TITLE
Console errors and no items above chests with new update

### ISSUE THREAD

**Issue by R176** [snowgears/shopbugs#122]
I get this any time people interact with shop chests, but they still work. 

[05:33:06 ERROR]: Could not pass event PlayerInteractEvent to Shop v1.8.2
java.lang.ClassCastException: class org.bukkit.material.MaterialData cannot be cast to class org.bukkit.material.Sign (org.bukkit.material.MaterialData and org.bukkit.material.Sign are in unnamed module of loader 'app')
at com.snowgears.shop.display.Display.getItemDropLocation(Display.java:255) ~[?:?]
at com.snowgears.shop.display.Display.spawn(Display.java:75) ~[?:?]
at com.snowgears.shop.display.Display.setType(Display.java:197) ~[?:?]
at com.snowgears.shop.display.Display.cycleType(Display.java:222) ~[?:?]
at com.snowgears.shop.listener.ShopListener.onDisplayChange(ShopListener.java:102) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-148]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-148]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor316.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1448) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-148]
at java.lang.Thread.run(Thread.java:834) [?:?]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-148]
[05:33:09 ERROR]: Could not pass event PlayerInteractEvent to Shop v1.8.2
java.lang.ClassCastException: class org.bukkit.material.MaterialData cannot be cast to class org.bukkit.material.Sign (org.bukkit.material.MaterialData and org.bukkit.material.Sign are in unnamed module of loader 'app')
at com.snowgears.shop.display.Display.getItemDropLocation(Display.java:255) ~[?:?]
at com.snowgears.shop.display.Display.spawn(Display.java:75) ~[?:?]
at com.snowgears.shop.display.Display.setType(Display.java:197) ~[?:?]
at com.snowgears.shop.listener.ShopListener.onDisplayChange(ShopListener.java:102) ~[?:?]
at com.snowgears.shop.display.Display.cycleType(Display.java:222) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor316.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-148]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.2.jar:git-Paper-148]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1448) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-148]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-148]
at java.lang.Thread.run(Thread.java:834) [?:?]

Additionally, there are no items above chests anymore since I updated from the second-latest version which worked fine. 

**Version:**
Paper-148
Shop latest version 1.8.2

**Additional context**
Not sure what else to say, no idea what's going on. Am not smart.

**Comment by R176** [comment]
Also I followed the instructions, deleted the signconfig and the other one

**Comment by snowgears** [comment]
Same as #127 . Fixed in 1.8.2.1
