### ISSUE TITLE
Shop on 1.15.2 

### ISSUE THREAD

**Issue by itsaderm** [snowgears/shopbugs#123]
**Describe the bug**
Plugin will not load on 1.15.2 server

**To Reproduce**
Use a 1.15.2 server and try load the plugin

**Expected behavior**
To load haha

**Screenshots**
`[22:32:15] [Server thread/ERROR]: Could not load 'plugins/Shop.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
	at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Purpur-606]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Purpur-606]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:272) ~[patched_1.15.2.jar:git-Purpur-606]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.15.2.jar:git-Purpur-606]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Version:**
 - Spigot version: [Paper 1.15.2]
 - Shop version [Latest]

**Additional context**

**Comment by XxMissGueraxX** [comment]
The 1.16 version of this plugin (latest) is not compatible with 1.15.2

**Comment by itsaderm** [comment]
Okay, what version supports 1.15.2 and are you able to add info as such to which version works with what server version etc?

**Comment by itsaderm** [comment]
Figured it out via the updates page. Info could be clearer though. Thank you :)

**Comment by snowgears** [comment]
I will try to make that more clear on the main page!
