### ISSUE TITLE
Another error message in the console

### ISSUE THREAD

**Issue by MrKiller01** [snowgears/shopbugs#135]
**Describe the bug**
Regarding https://github.com/snowgears/shopbugs/issues/69
After 19 days, sorry, been busy, ive downloaded the newest version :)  1.8.2.1,  and restarted my server.

**To Reproduce**
put shop.jar in plugins folder, 
stop server, 
rename the older one .jar1
start server 

**Expected behavior**
actually, no error at all, that would be nice...... :)

**Screenshots**
see below...

**Version:**
[19:07:59] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-b5a13e6-a939fbd (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[19:07:59] [Server thread/INFO]: Checking version, please wait...
[19:08:00] [Thread-85/INFO]: You are running the latest version
>
[19:08:39] [Server thread/INFO]: Shop version 1.8.2.1
[19:08:39] [Server thread/INFO]: Easily create shops to buy or sell items!
[19:08:39] [Server thread/INFO]: Author: Tanner Embry (SnowGears)
>

**Additional context**
[18:56:00] [Server thread/WARN]: [Shop] Task #194 for Shop v1.8.2.1 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
        at com.snowgears.shop.display.Display.setType(Display.java:197) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$5.run(ShopHandler.java:495) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[18:56:08] [Server thread/WARN]: [Shop] Task #484 for Shop v1.8.2.1 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler.refreshShopDisplays(ShopHandler.java:237) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$4.run(ShopHandler.java:428) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
>

**Comment by snowgears** [comment]
Can you please zip up your world file containing the shops and also zip up your Data folder in plugins/Shop? I will be able to better track down this specific error if I have both of these things. Thanks!

**Comment by MrKiller01** [comment]
Hi, I am sorry for the delay, but I am trying to put 6 GB online somewhere, and there are virtually no ways to do this without paying a lot of money.... however, I do have a website, and I will try to put it there for you to download... I have too little time to setup the ftp, so, is that ok by you? or do you have a free solution?

**Comment by MrKiller01** [comment]
Again, I tried several things, but I can't find the right solution for my website or any other way....
Is there a place on the Internet where I can store 7 GB without any fuzz? that you know of? 
I'm a bit ashamed that I can not do it by myself, I forgot the way Joomla worked and my windows server won't help, sorry....

**Comment by snowgears** [comment]
Will google drive support this large of a file? I know you get like 50gb free with any google account

**Comment by MrKiller01** [comment]
How stupid of me.... and come to think of it, I pay every year for larger storage for my email and google drive.... shame on me....
I let you know here when the files are there for you to pick up....
There are three files, one with all the worlds on that server; NH.rar
One with only one default world; World.rar
and ofcourse the plugin folder file.....
By the time (2 hours from now approx.) it is finished, I'll let you know.
Thanks for thinking along......

**Comment by MrKiller01** [comment]
Here it is.... 
https://drive.google.com/drive/folders/14HeHgBWliIj2D3JaqpnbQs5WgmJRL15z?usp=sharing

hope you succeed in getting it.....

**Comment by snowgears** [comment]
Just requested access on google.

**Comment by MrKiller01** [comment]
..... so that means that you can get the files?

**Comment by MrKiller01** [comment]
ok, then when you enter the world, at the spawn point (a big building, glass and concrete, has 3 layers (coordinates are around 0,0,0 if you are not seeing NEW NEW NEW HOLLAND etc...) on the top floor there are shops in the open air) there are signs (warp to different locations, if you search for a chest shop (if you need to do that)(idk, I have no knowledge how you approach this problem)

For what it is worth, I use this plugin on two of my servers, in the past the server Amigos had error messages (I looked over the logs recently and did find none on that server)
On the NH world, out of the blue, it has errors. So, if there is anything you need me to do, I am happy to help...

Thanks for your support, much appreciated........

**Comment by MrKiller01** [comment]
Got the new version of shop running, 1.8.2.2 and on Amigos server it gave an error...
[20:38:20] [Server thread/WARN]: [Shop] Task #209 for Shop v1.8.2.2 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
        at com.snowgears.shop.display.Display.setType(Display.java:197) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$5.run(ShopHandler.java:495) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[20:38:25] [Server thread/WARN]: [Shop] Task #498 for Shop v1.8.2.2 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler.refreshShopDisplays(ShopHandler.java:237) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$4.run(ShopHandler.java:428) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

I read that you closed it? but here i found no text from you.... ah well, the internet of mysteries,.....

**Comment by snowgears** [comment]
Closing this out as all displays have been fixed with packets now
