### ISSUE TITLE
Support stock placeholder on sign

### ISSUE THREAD

**Issue by iampug** [snowgears/shopbugs#137]
**Is your feature request related to a problem? Please describe.**
After adding stock placeholder in shop config. The plugin will fail to create shop. 
```
      normal:
         1: "&l[SELL] [stock]"
         2: "[item]"
         3: "Selling: &l[amount]"
         4: "Per &b[price]"
```
**Describe the solution you'd like**
I would like to have stock display on sign rather than clicking on chest to show.

**Additional context**
This is the error:
```
[08:07:53 ERROR]: Could not pass event SignChangeEvent to Shop v1.8.2.1
java.lang.NullPointerException: null
        at com.snowgears.shop.AbstractShop.getInventory(AbstractShop.java:106) ~[?:?]
        at com.snowgears.shop.AbstractShop.getStock(AbstractShop.java:88) ~[?:?]
        at com.snowgears.shop.util.ShopMessage.formatMessage(ShopMessage.java:138) ~[?:?]
        at com.snowgears.shop.util.ShopMessage.getSignLines(ShopMessage.java:209) ~[?:?]
        at com.snowgears.shop.SellShop.<init>(SellShop.java:20) ~[?:?]
        at com.snowgears.shop.listener.MiscListener.onShopCreation(MiscListener.java:223) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Purpur-747]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Purpur-747]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Purpur-747]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2757) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:41) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.PacketPlayInUpdateSign.a(SourceFile:9) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1203) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1172) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1016) ~[patched_1.16.2.jar:git-Purpur-747]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.2.jar:git-Purpur-747]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```

**Comment by snowgears** [comment]
Fixed in 1.8.2.2 (still in development).

Shops now support the '[stock]' tag and the signs dynamically update when this tag is used.
