### ISSUE TITLE
Plugin will not load

### ISSUE THREAD

**Issue by dylanmcfarlin** [snowgears/shopbugs#14]
[Server thread/INFO]: [Shop] Shops will use emerald as the currency on the server.
[20:27:57] [Server thread/ERROR]: Error occurred while enabling Shop v1.8.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.RED_STAINED_GLASS_PANE
	at java.base/java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
	at org.bukkit.Material.valueOf(Material.java:1) ~[spigot18.jar:git-PaperSpigot-"4c7641d"]
	at com.snowgears.shop.handler.ShopGuiHandler.loadIconsAndTitles(ShopGuiHandler.java:226) ~[?:?]
	at com.snowgears.shop.handler.ShopGuiHandler.<init>(ShopGuiHandler.java:46) ~[?:?]
	at com.snowgears.shop.Shop.onEnable(Shop.java:242) ~[?:?]

**Comment by Doxify** [comment]
server version is paper-spigot 1.8, is there a link for a 1.8 compatible version?

**Comment by snowgears** [comment]
Please remove the config files and use a shop version compatible with Spigot 1.12 (anything below shop version 1.8)
