### ISSUE TITLE
[Server thread/WARN]: [Shop] Task #80 for Shop v1.8.2.4 generated an exception

### ISSUE THREAD

**Issue by chung12322** [snowgears/shopbugs#202]
[05:01:50] [Server thread/WARN]: [Shop] Task #80 for Shop v1.8.2.4 generated an exception
java.lang.IllegalStateException: Start block missed in BlockIterator
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:171) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:236) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:277) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:178) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:200) ~[patched_1.16.5.jar:git-Paper-468]
	at com.snowgears.shop.listener.DisplayListener.lambda$startRepeatingDisplayViewTask$0(DisplayListener.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-468]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Version:**
 - Spigot version: paper 1.16.5
 - Shop version: 1.8.2.4

**Additional context**

**Comment by snowgears** [comment]
Fixed in 1.8.2.5 (in progress)

**Comment by VytskaLT** [comment]
> Fixed in 1.8.2.5 (in progress)

This is unrelated to this plugin, but I wanted to ask you how you fixed this? I'm having the same issue with my plugin and I have no idea how to fix it.

**Comment by snowgears** [comment]
I just catch the exception and chalk it up to the block iterator not finding a block or something going wrong when it tries.
`try {
                            Block block = player.getTargetBlock(null, 8);
                            if (block.getBlockData() instanceof WallSign) {
                                AbstractShop shopObj = plugin.getShopHandler().getShop(block.getLocation());
                                if (shopObj != null) {
                                    shopObj.getDisplay().showDisplayTags(player);
                                }
                            }
                        } catch (IllegalStateException e) {
                            //do nothing, the block iterator missed a block for a player
                        }`
