### ISSUE TITLE
shops wiped from null pointer read in config

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#262]
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "<local4>" is null
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.Shop.getPriceString(Shop.java:560)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.shop.AbstractShop.getPricePerItemString(AbstractShop.java:240)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.util.ShopMessage.formatMessage(ShopMessage.java:159)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.util.ShopMessage.getSignLines(ShopMessage.java:283)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.shop.SellShop.<init>(SellShop.java:22)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.shop.AbstractShop.create(AbstractShop.java:108)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.handler.ShopHandler.loadShopsFromConfig(ShopHandler.java:771)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.handler.ShopHandler.access$400(ShopHandler.java:35)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at Shop-1.8.3.1(1).jar//com.snowgears.shop.handler.ShopHandler$4.run(ShopHandler.java:701)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[18:43:44] [Craft Scheduler Thread - 6 - Shop/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by snowgears** [comment]
reopen if this happens again
