### ISSUE TITLE
itemstack NMS mouse-hover broken in 1.18

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#270]
1.18 NMS changes broke mouse hover for hovering over an itemstack in chat.

`[20:43:33 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.save(net.minecraft.nbt.NBTTagCompound)
[20:43:33 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[20:43:33 WARN]:        at Shop-1.8.3.2.jar//com.snowgears.shop.util.ReflectionUtil.getMethod(ReflectionUtil.java:198)
[20:43:33 WARN]:        at Shop-1.8.3.2.jar//com.snowgears.shop.util.ReflectionUtil.convertItemStackToJson(ReflectionUtil.java:256)
[20:43:33 WARN]:        at Shop-1.8.3.2.jar//com.snowgears.shop.shop.AbstractShop.formatAndSendFancyMessage(AbstractShop.java:488)
[20:43:33 WARN]:        at Shop-1.8.3.2.jar//com.snowgears.shop.shop.AbstractShop.printSalesInfo(AbstractShop.java:457)
[20:43:33 WARN]:        at Shop-1.8.3.2.jar//com.snowgears.shop.listener.ShopListener.onShopOpen(ShopListener.java:184)
[20:43:33 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor377.execute(Unknown Source)
[20:43:33 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:43:33 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:43:33 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:43:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[20:43:33 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[20:43:33 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:540)
[20:43:33 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1754)
[20:43:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[20:43:33 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[20:43:33 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[20:43:33 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:43:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[20:43:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[20:43:33 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[20:43:33 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[20:43:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[20:43:33 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[20:43:33 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[20:43:33 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[20:43:33 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1462)
[20:43:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[20:43:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[20:43:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by snowgears** [comment]
Fixed in 1.8.3.3
