### ISSUE TITLE
1.8.3.3 - item hover broken in 1.17

### ISSUE THREAD

**Issue by snowgears** [snowgears/shopbugs#278]
[17:34:19 INFO]: Purzel2010 issued server command: /shop
[17:34:51 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.b(net.minecraft.nbt.NBTTagCompound)
[17:34:51 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2195)
[17:34:51 WARN]:        at Shop-1.8.3.3.jar//com.snowgears.shop.util.ReflectionUtil.getMethod(ReflectionUtil.java:198)
[17:34:51 WARN]:        at Shop-1.8.3.3.jar//com.snowgears.shop.util.ReflectionUtil.convertItemStackToJson(ReflectionUtil.java:256)
[17:34:51 WARN]:        at Shop-1.8.3.3.jar//com.snowgears.shop.shop.AbstractShop.formatAndSendFancyMessage(AbstractShop.java:488)
[17:34:51 WARN]:        at Shop-1.8.3.3.jar//com.snowgears.shop.shop.AbstractShop.printSalesInfo(AbstractShop.java:457)
[17:34:51 WARN]:        at Shop-1.8.3.3.jar//com.snowgears.shop.listener.ShopListener.onShopOpen(ShopListener.java:184)
[17:34:51 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor455.execute(Unknown Source)
[17:34:51 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:34:51 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:34:51 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:34:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[17:34:51 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[17:34:51 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
[17:34:51 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1815)
[17:34:51 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[17:34:51 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[17:34:51 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[17:34:51 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:34:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[17:34:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[17:34:51 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[17:34:51 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[17:34:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[17:34:51 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[17:34:51 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[17:34:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[17:34:51 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1536)
[17:34:51 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[17:34:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:34:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by snowgears** [comment]
Fixed in 1.8.3.4 (in progress)
