### ISSUE TITLE
Eco enchantments compatibility

### ISSUE THREAD

**Issue by Liama669** [snowgears/shopbugs#281]
When an item has an EcoEnchants enchantment applies, it appears as unknown in the chat menu, and will not appear at all when you hover over the item.

https://cdn.discordapp.com/attachments/366414179416145920/923114840166375424/unknown.png

**Comment by snowgears** [comment]
Looked into adding support and got hit with this error

`[22:58:47 ERROR]: [eco] Unhandled exception occured in onPacketSending(PacketEvent) for eco
java.lang.IllegalAccessError: class com.willfp.eco.internal.spigot.proxy.v1_17_R1.fast.NMSFastItemStack tried to access private field net.minecraft.world.item.ItemStack.u (com.willfp.eco.internal.spigot.proxy.v1_17_R1.fast.NMSFastItemStack is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3d294941; net.minecraft.world.item.ItemStack is in unnamed module of loader 'app')
    at com.willfp.eco.internal.spigot.proxy.v1_17_R1.fast.NMSFastItemStack.hashCode(NMSFastItemStack.kt:179) ~[?:?]
    at com.willfp.eco.internal.spigot.display.PacketWindowItems.modifyWindowItems(PacketWindowItems.kt:140) ~[?:?]`

May look at adding support for another more popular enchant plugin like [CrazyEnchants](https://www.spigotmc.org/resources/crazy-enchantments.16470/)

**Comment by ToonamiSenpai** [comment]
https://www.taako-senpai.xyz/Fo5X6v.png
It works just not the name being hooked

**Comment by snowgears** [comment]
Now that I use an NBT API, I will look into adding support for custom enchantments / custom (visible) NBT tags

**Comment by OstlerDev** [comment]
Released in v1.10.0
