### ISSUE TITLE
My server is 1.12.2

### ISSUE THREAD

**Issue by PabloKoutaNya** [snowgears/shopbugs#3]
[14:43:15 ERROR]: Error occurred while enabling Shop v1.8.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.RED_STAINED_GLASS_PANE
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_181]
        at org.bukkit.Material.valueOf(Material.java:71) ~[patched_1.12.2.jar:git-Paper-1594]
        at com.snowgears.shop.handler.ShopGuiHandler.loadIconsAndTitles(ShopGuiHandler.java:226) ~[?:?]
        at com.snowgears.shop.handler.ShopGuiHandler.<init>(ShopGuiHandler.java:46) ~[?:?]
        at com.snowgears.shop.Shop.onEnable(Shop.java:242) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1594]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1594]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1594]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1594]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1594]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1594]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1594]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1594]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1594]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1594]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by snowgears** [comment]
You are running the 1.13 version of the plugin on a 1.12 server.

**Comment by PabloKoutaNya** [comment]
What version download for 1.12?

**Comment by snowgears** [comment]
1.7.3.2 is the latest version compatible with Minecraft 1.12 and below
