### ISSUE TITLE
Connection leak detected? 

### ISSUE THREAD

**Issue by therealatsuga** [snowgears/shopbugs#314]
Hi
This warning is showing up in the startup log

`[07:58:19] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@1e475c65 on thread Server thread, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[Shop-1.8.3.6.jar:?]
	at com.snowgears.shop.handler.LogHandler.initDb(LogHandler.java:276) ~[Shop-1.8.3.6.jar:?]
	at com.snowgears.shop.handler.LogHandler.<init>(LogHandler.java:44) ~[Shop-1.8.3.6.jar:?]
	at com.snowgears.shop.Shop.onEnable(Shop.java:388) ~[Shop-1.8.3.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:58:19] [HikariPool-1 housekeeper/WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@67bda197 on thread Server thread, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[Shop-1.8.3.6.jar:?]
	at com.snowgears.shop.handler.LogHandler.initDb(LogHandler.java:276) ~[Shop-1.8.3.6.jar:?]
	at com.snowgears.shop.handler.LogHandler.<init>(LogHandler.java:44) ~[Shop-1.8.3.6.jar:?]
	at com.snowgears.shop.Shop.onEnable(Shop.java:388) ~[Shop-1.8.3.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1614]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

[https://codeshare.io/X8dewM](https://codeshare.io/X8dewM)

I hope this is nothing serious. 

Tywm for your work.

**Comment by Cruwzky** [comment]
This also spams my console on each start. Are there any ETA one a solution?

`[21:35:15 WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@3404b9c5 on thread Server thread, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[Shop-1.8.3.6.jar:?]
        at com.snowgears.shop.handler.LogHandler.initDb(LogHandler.java:276) ~[Shop-1.8.3.6.jar:?]
        at com.snowgears.shop.handler.LogHandler.<init>(LogHandler.java:44) ~[Shop-1.8.3.6.jar:?]
        at com.snowgears.shop.Shop.onEnable(Shop.java:388) ~[Shop-1.8.3.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:35:15 INFO]: Preloaded 10 players data in 0.19
[21:35:15 WARN]: [com.zaxxer.hikari.pool.ProxyLeakTask] Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@c31bf47 on thread Server thread, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[Shop-1.8.3.6.jar:?]
        at com.snowgears.shop.handler.LogHandler.initDb(LogHandler.java:276) ~[Shop-1.8.3.6.jar:?]
        at com.snowgears.shop.handler.LogHandler.<init>(LogHandler.java:44) ~[Shop-1.8.3.6.jar:?]
        at com.snowgears.shop.Shop.onEnable(Shop.java:388) ~[Shop-1.8.3.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:35:17 INFO]: [com.zaxxer.hikari.pool.ProxyLeakTask] Previously reported leaked connection com.mysql.cj.jdbc.ConnectionImpl@3404b9c5 on thread Server thread was returned to the pool (unleaked)
[21:35:17 INFO]: [com.zaxxer.hikari.pool.ProxyLeakTask] Previously reported leaked connection com.mysql.cj.jdbc.ConnectionImpl@c31bf47 on thread Server thread was returned to the pool (unleaked)`

**Comment by snowgears** [comment]
This will be fixed in the next update!

**Comment by snowgears** [comment]
Fixed in 1.8.3.7 (in progress)
