### ISSUE TITLE
Shop not leading

### ISSUE THREAD

**Issue by Endergirl2900** [snowgears/shopbugs#34]
**Describe the bug**
The jar file isn't loading

**Screenshots**
 [12:54:42] [Server thread/ERROR]: Could not load 'plugins/Shop.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot1132.jar:git-Spigot-a1f2566-a4c555b]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot1132.jar:git-Spigot-a1f2566-a4c555b]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:323) [spigot1132.jar:git-Spigot-a1f2566-a4c555b]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot1132.jar:git-Spigot-a1f2566-a4c555b]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot1132.jar:git-Spigot-a1f2566-a4c555b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.util.zip.ZipException: zip file is empty
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_191]
at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_191]
at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_191]
at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_191]
at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_191]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot1132.jar:git-Spigot-a1f2566-a4c555b]
... 5 more

**Version:**
Spigot 1.13.2
using latest version of the plugin

What can i do ? :D

**Comment by snowgears** [comment]
It appears that you are attempting to install the plugin wrong. Can you remove any files relating to shop from your server plugins folder and then drop the default jar file provided in there and restart your server?

**Comment by snowgears** [comment]
Closed until question is answered.
