### ISSUE TITLE
[BUG] Enderchests storing

### ISSUE THREAD

**Issue by SladeHazard** [snowgears/shopbugs#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Data loss, Other unexpected behaviour

### Environment

```markdown
- Server Version: 1.12.2 Paper
- Shop Version: 1.8.4-legacy

Why is this plugin storing people's enderchest in a data folder? when it's supposed to be managed by world/playerdata folder files. is there any way I can disable this?
```

### Server startup log

N/A

### Shop config files

N/A

### Error log (if applicable)

N/A

### Bug description

The plugin is storing people's enderchests for no reason. and I can't find an option to disable it

### Steps to reproduce

load this plugin on the server

### Expected behaviour

not store enderchests, it's unnecessary 

### Actual behaviour

stores people's enderchests even if i clear their playerdata from the world folder

### Other information

also another I noticed since I have this plugin people have been getting each other's enderchest instead of their original ones after server restarts.

**Comment by SladeHazard** [comment]
also this error appears on 1.12.2

 [21:21:18 INFO]: kinkles issued server command: /warp pvp
>
 [21:21:18 WARN]: [Shop] Task #16502964 for Shop v1.8.4 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between Archer and ArcherPlots
        at org.bukkit.Location.distanceSquared(:469) ~[server.jar:git-Paper-2116373]
        at com.snowgears.shop.display.AbstractDisplay.playerIsLookingTowardShop(AbstractDisplay.java:445) ~[?:?]
        at com.snowgears.shop.display.AbstractDisplay$1.run(AbstractDisplay.java:468) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(:64) ~[server.jar:git-Paper-2116373]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(:423) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(:844) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(:431) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(:778) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(:669) ~[server.jar:git-Paper-2116373]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by snowgears** [comment]
Fixed error being reported in 1.8.4.1 (in progress)

**Comment by SladeHazard** [comment]
. the error wasn't the main issue, i just added it to the same issue

**Comment by snowgears** [comment]
You can disable enderchests being used in shops by removing the ENDER_CHEST from the main config file in the container list

**Comment by snowgears** [comment]
You can disable enderchests being used in shops by removing the ENDER_CHEST from the main config file in the container list
