### ISSUE TITLE
[BUG] Shops are reset whenever the server is restarted.

### ISSUE THREAD

**Issue by ByoneWorld** [snowgears/shopbugs#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Type of bug

Performance issue or memory leak

### Environment

```markdown
- Server Version: 1.20.4
- Shop Version: 1.9.1.2
```

### Server startup log

https://paste.gg/p/anonymous/d7f0a9632fa04d48ab7a490fb7468233

### Shop config files

https://paste.gg/p/anonymous/322609ea75f1409b8383dee84994fa5e

### Bug description

Everytime I restart the server, players need to reset their signs for the shop to be active.

### Steps to reproduce

Restart the server

### Expected behaviour

Shops should save

### Actual behaviour

When I restart the server, shops reset.

**Comment by MaechtigerMatthias** [comment]
same problem. Not for all, but for a lot of players.

**Comment by SiuanSong** [comment]
I've had this happen two or three times as well. I haven't found any sort of reason why, but rarely on restart Shops will not load the players shop files it seems. If we simply restart again, the files all load as they should. But if a player remakes a shop while this is "broken" it resets their shop file and all other shop chest info is lost.

**Comment by Mackenzie2346** [comment]
Have come across the same issue today.

Admin shops are breaking when server is restarted :(

And by breaking I mean this:

![image](https://github.com/user-attachments/assets/0824c389-b238-45e8-bc09-43d558ac1586)

I right click on the sign to sell, and rather then it saying the default "you don't have item to sell" it says this (see image).

**Comment by OstlerDev** [comment]
I am sorry for the very delayed fix on this bug, I have been really struggling to replicate the issue which has been making it difficult to confirm the actual issue. This fix is very important and planned, and I will get to it as soon as I can!

**Comment by tonyjamesstark** [comment]
A few more details, it appears that it's inconsistent which shops aren't loaded properly, but each day after restart, there are many that players cannot use and have behavior similar to the screenshot above.  

for context, the server where Siuan and I have observed the issue has a fairly large player base, with upwards of 2800 shops, many with very extensive custom item data (lore, names, color codes, attribute modifiers, enchants). We use an item economy (diamonds), and are not using displays. 

If you need further info, happy to provide!

**Comment by tonyjamesstark** [comment]
upon reloading a bunch of these messages also appear in console:
`[17:30:55 WARN]: Couldn't look up profile properties for <uuid redacted>
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read value <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta content='text/html; charset=utf-8' http-equiv='content-type' />
    <style type='text/css'>
        body {
            font-family: Arial;
            margin-left: 40px;
        }
        img {
            border: 0 none;
        }
        #content {
            margin-left: auto;
            margin-right: auto
        }
        #message h2 {
            font-size: 20px;
            font-weight: normal;
            color: #000000;
            margin: 34px 0px 0px 0px
        }
        #message p {
            font-size: 13px;
            color: #000000;
            margin: 7px 0px 0px0px
        }
        #errorref {
            font-size: 11px;
            color: #737373;
            margin-top: 41px
        }
    </style>
    <title>Service unavailable</title>
</head>
<body>
    <div id='content'>
        <div id='message'>
            <h2>The request is blocked.</h2>
        </div>
        <div id='errorref'>
            <span>20241219T173055Z-17f6b595578zmn78hC1BN1sync0000000stg0000000087xa            </span>
        </div>
    </div>
</body>
</html>
        at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:32) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:99) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfileUncached(YggdrasilMinecraftSessionService.java:201) ~[authlib-6.0.54.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfile(YggdrasilMinecraftSessionService.java:171) ~[authlib-6.0.54.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fetchProfile(PaperMinecraftSessionService.java:35) ~[purpur-1.21.1.jar:1.21.1-2306-bc7bcbb]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.getUpdatedProfile(CraftPlayerProfile.java:155) ~[purpur-1.21.1.jar:1.21.1-2306-bc7bcbb]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
        at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30) ~[authlib-6.0.54.jar:?]
        ... 10 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
        at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30) ~[authlib-6.0.54.jar:?]
        ... 10 more`

**Comment by tonyjamesstark** [comment]
upon reloading the shop a bunch of these messages pop up in console (one example attached). multiple UUIDs, different each time. appears to be something throttling requests for profile lookup
[shop_profile_lookup_error.txt](https://github.com/user-attachments/files/18201427/shop_profile_lookup_error.txt)

**Comment by Mackenzie2346** [comment]
I tested the plugin on 1.20.6 purpur rather than 1.20.4 purpur and this issue mentioned above is only present on 1.20.4, but isn't an issue when reloading the server in 1.20.6, hope this information can help! :)

**Comment by tonyjamesstark** [comment]
We have been experiencing this issue on 1.21.1 since the beginning

**Comment by OstlerDev** [comment]
Fixed in v1.10.0!
