### ISSUE TITLE
org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by kuba3234** [snowgears/shopbugs#47]
When i put sign in front of chest and write 
[shop]
2
2

sign dissapear
and when i write /shop and hit enter it just says on chat
/shop
server engine is spigot 1.13.2  but it was on bukkit

[17:47:25 ERROR]: Could not pass event SignChangeEvent to Shop v1.4.8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2354) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
	at com.snowgears.shop.listeners.MiscListener.onSignEdit(MiscListener.java:188) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	... 15 more
[17:53:01 WARN]: [Shop] Plugin Shop v1.4.8 generated an exception while executing task 2
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.snowgears.shop.utils.Metrics.postPlugin(Metrics.java:363) ~[?:?]
	at com.snowgears.shop.utils.Metrics.access$5(Metrics.java:354) ~[?:?]
	at com.snowgears.shop.utils.Metrics$1.run(Metrics.java:255) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[17:54:33 ERROR]: Could not pass event SignChangeEvent to Shop v1.4.8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2354) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:44) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PacketPlayInUpdateSign.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
	at com.snowgears.shop.listeners.MiscListener.onSignEdit(MiscListener.java:188) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	... 15 more

**Comment by BillyGalbreath** [comment]
Fixed in next release
