### ISSUE TITLE
there is no 1.8 SUPPORT

### ISSUE THREAD

**Issue by kingOf0** [snowgears/shopbugs#54]
there's no PLAYER_HEAD in 1.8
it causes stack trace on server start

`[23:15:42 ERROR]: Error occurred while enabling Shop v1.8.0.1 (Is it up to date?
)
java.lang.NoSuchFieldError: PLAYER_HEAD
        at com.snowgears.shop.handler.ShopGuiHandler.loadIconsAndTitles(ShopGuiH
andler.java:233) ~[?:?]
        at com.snowgears.shop.handler.ShopGuiHandler.<init>(ShopGuiHandler.java:
46) ~[?:?]
        at com.snowgears.shop.Shop.onEnable(Shop.java:242) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[P
aperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:332) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"
]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:407) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d
"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:359) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:318) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]

        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:4
08) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:3
72) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:3
27) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.jav
a:267) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:563) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Version:**
 - Spigot version: [e.g. Spigot 1.8.8]
 - Shop version [e.g. 1.8.0.1]

**Comment by kingOf0** [comment]
I downloaded Shop 1.7.3.2 and deleted files, nothing changed it still crashes server.

[logs.txt](https://github.com/snowgears/shopbugs/files/3268251/logs.txt)

**Comment by snowgears** [comment]
Fixed in Shop 1.8.2 (in progress)
