### ISSUE TITLE
Inv Gui doesn't work

### ISSUE THREAD

**Issue by d0nghan** [snowgears/shopbugs#56]
**Describe the bug**
Inv Gui doesn't work

**To Reproduce**
1. /shop and click "admin" shop
2. [11:10:31 INFO]: D_Han_ issued server command: /shop
[11:10:37 ERROR]: Could not pass event InventoryClickEvent to Shop v1.8.0.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:507) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:492) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.jav
a:2108) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33
) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10
) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerCo
nnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1
.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
896) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
831) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoSuchFieldError: STAINED_GLASS_PANE
        at com.snowgears.shop.gui.ShopGuiWindow.getNextPageIcon(ShopGuiWindow.ja
va:163) ~[?:?]
        at com.snowgears.shop.gui.ListShopsWindow.initInvContents(ListShopsWindo
w.java:67) ~[?:?]
        at com.snowgears.shop.gui.ListShopsWindow.<init>(ListShopsWindow.java:31
) ~[?:?]
        at com.snowgears.shop.gui.ShopGUIListener.onInvClick(ShopGUIListener.jav
a:123) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        ... 15 more
>

**Expected behavior**
I make 2 same shop. It buy same item, but it's different number of items. (looks like Screen Shot)

**Screenshots**
https://cafe.naver.com/itsmyname/986

**Version:**
 - Spigot 1.13.2
 - Shop version [1.8.0.1]

**Additional context**

**Comment by BillyGalbreath** [comment]
Fixed in next release
