### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by msburgess3200** [snowgears/shopbugs#58]
[13:44:12] [Server thread/ERROR]: Could not pass event InventoryCreativeEvent to
 Shop v1.8.0.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:320) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:529) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:514) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.jav
a:2324) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFil
e:23) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PacketPlayInSetCreativeSlot.a(SourceFil
e:9) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerCo
nnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.1
4.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFil
e:135) [spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(
SourceFile:23) [spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFil
e:114) [spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java
:898) [spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftSe
rver.java:891) [spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile
:123) [spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftS
erver.java:875) [spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:808) [spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle(
)Ljava/lang/String;
        at com.snowgears.shop.gui.ShopGUIListener.onInvClick(ShopGUIListener.jav
a:37) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-eb2e657]
        ... 17 more
>

**Version:**
 - Spigot version: 1.14.3 (1.14.3-R0.1-SNAPSHOT)
 - Shop version Latest available from Spigotmc.org.

**Comment by BillyGalbreath** [comment]
Latest version a available from Spigotmc.org does not list 1.14.3 as a supported version.

Not a bug.
