### ISSUE TITLE
command not working on paperspigot

### ISSUE THREAD

**Issue by KingGoldensPanda** [snowgears/shopbugs#6]
[01:44:01 INFO]: [Shop] Enabling Shop v1.8.0.1
[01:44:02 INFO]: [Shop] Vault dependency found. Using the Vault economy ($) for currency on the server.
[01:44:02 ERROR]: Error occurred while enabling Shop v1.8.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.166
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_181]
        at org.bukkit.Material.valueOf(Material.java:75) ~[patched_1.13.2.jar:git-Paper-481]
        at com.snowgears.shop.handler.ShopGuiHandler.loadIconsAndTitles(ShopGuiHandler.java:226) ~[?:?]
        at com.snowgears.shop.handler.ShopGuiHandler.<init>(ShopGuiHandler.java:46) ~[?:?]
        at com.snowgears.shop.Shop.onEnable(Shop.java:242) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-481]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-481]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-481]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-481]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-481]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-481]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-481]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[01:44:02 INFO]: [Shop] Disabling Shop v1.8.0.1

[01:45:47 INFO]: KingGoldensPanda issued server command: /chestshop
[01:45:47 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'chestshop' in com.snowgears.shop.handler.CommandHandler(chestshop)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.13.2.jar:git-Paper-481]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-481]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-481]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-481]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at com.snowgears.shop.handler.CommandHandler.execute(CommandHandler.java:40) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-481]
        ... 14 more

**Comment by snowgears** [comment]
It appears you are using paperspigot which has trouble registering commands (shop registers a custom 'shop' command). Please try with regular spigot to confirm bug.
