### ISSUE TITLE
Bug 1.14 Update

### ISSUE THREAD

**Issue by Marcobohl** [snowgears/shopbugs#62]
[00:04:50] [Server thread/INFO]: [Shop] Enabling Shop v1.8.1
[00:04:50] [Server thread/INFO]: [Shop] Vault dependency found. Using the Vault economy ($) for currency on the server.
[00:04:50] [Server thread/ERROR]: Error occurred while enabling Shop v1.8.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.166
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_171]
	at org.bukkit.Material.valueOf(Material.java:1) ~[spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at com.snowgears.shop.handler.ShopGuiHandler.loadIconsAndTitles(ShopGuiHandler.java:221) ~[?:?]
	at com.snowgears.shop.handler.ShopGuiHandler.<init>(ShopGuiHandler.java:53) ~[?:?]
	at com.snowgears.shop.Shop.onEnable(Shop.java:245) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot.jar:git-Spigot-ea7e48b-368f4e9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by BillyGalbreath** [comment]
Backup and delete your GuiConfig.yml file then restart your server to let the plugin generate a new one.

**Comment by Marcobohl** [comment]
Thanks for the update and the quick help. Was that in the update description? if not you could insert that yet / Minecraft version 1.1.4.4 is Working
