### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by MrKiller01** [snowgears/shopbugs#69]
[19:00:27] [Server thread/WARN]: [Shop] Task #337 for Shop v1.8.1 generated an e
xception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:48) ~[?:?]
        at com.snowgears.shop.display.Display.setType(Display.java:182) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$4.run(ShopHandler.java:446) ~[
?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.jav
a:81) ~[spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:
1022) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:
393) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:
970) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:815) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[19:00:38] [Server thread/WARN]: [Shop] Task #581 for Shop v1.8.1 generated an e
xception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:48) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler.refreshShopDisplays(ShopHandle
r.java:240) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$3.run(ShopHandler.java:382) ~[
?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.jav
a:81) ~[spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:
1022) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:
393) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:
970) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:815) [spigot-1.14.4.jar:git-Spigot-065a373-763e560]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
>

**To Reproduce**
1. Go to 'server console'
2. read the error message
3. select and copy
4. paste the error here....

**Expected behavior**
Well, not this behavior, that's for sure...

**Screenshots**
Thats where I started with... see top!

**Version:**
>ver
[09:22:37] [Server thread/INFO]: This server is running CraftBukkit version git-
Spigot-065a373-9aa7430 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSH
OT)
[09:22:37] [Server thread/INFO]: Checking version, please wait...
[09:22:38] [Thread-60/INFO]: You are running the latest version
>
>version shop
[09:27:52] [Server thread/INFO]: SignShop version 2.11.2
[09:27:52] [Server thread/INFO]: Author: Wargamer2010 and Devinish
**[09:27:52] [Server thread/INFO]: Shop version 1.8.1
[09:27:52] [Server thread/INFO]: Easily create shops to buy or sell items!
[09:27:52] [Server thread/INFO]: Author: Tanner Embry (SnowGears)**
>

**Additional context**
>pl
[09:22:31] [Server thread/INFO]: Plugins (44): dynmap, LuckPerms, WorldEdit, Ran
domTeleporter, AngelChest, WorldEditSUI, BlockLocker, PlaceholderAPI, PlugMan, S
pawnPlugin, BetterEnderChest, SetSpawn, WorldBorder, Multiverse-Core, ProtocolLi
b, DeathMessagesPrime, SimpleBackup, VPNGuard, VotingPlugin, RedstoneClockDetect
or, Multiverse-SignPortals, PhysicsToGo, CreeperHeal, mcMMO, Multiverse-Portals,
 Vault, SimplePortals, EZRanksPro, MysqlEcoBridge, Essentials, BKCommonLib, Parr
otAnnouncer, PreciousStones, SignShop, Plan, Train_Carts, EssentialsChat, Essent
ialsGeoIP, Shop, Multiverse-NetherPortals, EssentialsSpawn, TCHangRail, PluginLi
brary, Statz

**Comment by snowgears** [comment]
Please try shop version 1.8.2 with a compatible version of Spigot (1.16+) and reopen a ticket if this issue persists.
