### ISSUE TITLE
Several NullPointerException during startup, and problems with the shops

### ISSUE THREAD

**Issue by meres10** [snowgears/shopbugs#82]
We are upgrading from 1.12.2 to 1.15.1.
During the startup Shop drops a good number of exceptions.
Some chests are OK (e.g. selling red terracotta), but others are not.
One of our player is selling maps.
The Shop gives "air" instead of the certain map of the region.
Also, no holo item showcase were found, but there were out some.
(as far as I remember)

0. Start the server and check the log
1. Go to an upgraded Shop chest having "complicated" items like filled maps
2. Try to buy
3. You will get "air" instead of the goods.

Versions:

1.15.1 Java Edition (original) client
Paper version git-Paper-26 (MC: 1.15.1)

Log:
```
[13:38:40] [Server thread/WARN]: [Shop] Task #26 for Shop v1.8.1 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:48) ~[?:?]
        at com.snowgears.shop.display.Display.setType(Display.java:182) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$4.run(ShopHandler.java:446) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.ja
r:git-Paper-26]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-26]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-26]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-26]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-26]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-26]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by meres10** [comment]
Well, I think I've found the root of the problem.
Shop data of 1.12.2 is incompatible with 1.51.1, and no conversion was made.
- displayType: LARGE_ITEM disappeared
- Before the type of item a new stuff v: 2227 appeared (db version?)
- The type for MAP has changed to FILLED_MAP
- The map number as "damage: 106" changed to meta "map-id: 106"
etc...

An external  tool, or automatic upgrade of DB would be kindly appreciated.

**Comment by snowgears** [comment]
This is fixed in the latest update *current in progress"
