### ISSUE TITLE
ItemMeta is null in Spigot 1.13

### ISSUE THREAD

**Issue by MrKiller01** [snowgears/shopbugs#9]
[USER=55764]@SnowGears[/USER]
Been updating our servers and noticed on one of them an error... I deleted already the yaml file (renamed it actually) and let the plugin generate again a new one, still, the error keeps showing...
[code][09:46:36 WARN]: [Shop] Task #278 for Shop v1.8.0.1 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
        at com.snowgears.shop.display.Display.setType(Display.java:197) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$5.run(ShopHandler.java:449) ~[
?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.jav
a:81) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
893) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
835) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:733) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[09:46:40 WARN]: [Shop] Task #522 for Shop v1.8.0.1 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler.refreshShopDisplays(ShopHandle
r.java:240) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$4.run(ShopHandler.java:382) ~[
?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.jav
a:81) ~[spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
893) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
835) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:733) [spigot-1.13.2.jar:git-Spigot-078a7f5-7fa173e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191][/code]

Maybe you can tell us what to do....(-:

**Comment by MrKiller01** [comment]
The above is from a few days ago, and this here below is from today with the latest spigot.....

[13:00:12] [Server thread/WARN]: [Shop] Task #308 for Shop v1.8.0.1 generated an exception
java.lang.NullPointerException: null
	at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
	at com.snowgears.shop.display.Display.setType(Display.java:197) ~[?:?]
	at com.snowgears.shop.handler.ShopHandler$5.run(ShopHandler.java:449) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[13:00:15] [Server thread/WARN]: [Shop] Task #553 for Shop v1.8.0.1 generated an exception
java.lang.NullPointerException: null
	at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
	at com.snowgears.shop.handler.ShopHandler.refreshShopDisplays(ShopHandler.java:240) ~[?:?]
	at com.snowgears.shop.handler.ShopHandler$4.run(ShopHandler.java:382) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by GoogleSites** [comment]
Version? It looks like there is something wrong in your sign config

**Comment by MrKiller01** [comment]
Version of what? All the info is there.....spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd and Shop v1.8.0.1,
 and if there would be something wrong with signs, how do you think I am able to repair that? I don't know where the signs are, and what could there possibly go wrong with 4 lines on a sign that if there is one mistake, the sign does not do what the owner wants, so it does not work then, or generates the wrong trade.... In either cases, It would not work the way intended. 
Want me to go on???

**Comment by GoogleSites** [comment]
at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
at com.snowgears.shop.display.Display.setType(Display.java:197) ~[?:?]

Try setting the default sign value to only use a sign without a floating item on top

**Comment by MrKiller01** [comment]
@GoogleSites, nice of you to answer, but i'm having a hard time believing that I need to change the displaytype from GLASS_CASE to ....NONE????? , which is standard and untouched, the way I prefer things often.
But, I will try that, it is ofcourse an idea... Be back later....

**Comment by MrKiller01** [comment]
Ehm, now nobody can see what it is this person is selling, buying, trade or gamble.
Even that setting to NONE made a few chests appear no item floating above but a few still were...
Frankly, thisis not my idea, but I bought the plugin because of that floating item above it....
Help please......

**Comment by MrKiller01** [comment]
@GoogleSites I am sorry to inform you of this......

> [14:44:11 WARN]: [Shop] Task #312 for Shop v1.8.0.1 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
        at com.snowgears.shop.display.Display.setType(Display.java:197) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$5.run(ShopHandler.java:449) ~[
?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.jav
a:81) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
889) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[14:44:15 WARN]: [Shop] Task #557 for Shop v1.8.0.1 generated an exception
java.lang.NullPointerException: null
        at com.snowgears.shop.display.Display.spawn(Display.java:50) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler.refreshShopDisplays(ShopHandle
r.java:240) ~[?:?]
        at com.snowgears.shop.handler.ShopHandler$4.run(ShopHandler.java:382) ~[
?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.jav
a:81) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
889) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

>

**Comment by MrKiller01** [comment]
Your welcome.....

**Comment by snowgears** [comment]
This appears to be fixed in Shop v 1.8.2. If this new version does not fix your issue please reopen the ticket. Thanks!

**Comment by MrKiller01** [comment]
ehm, I think I mixed replies up.... The other problem you were working on, me putting 7 GB online for you, yes, that one, that one came back with an error on one of two servers.... (Added it to the bug list....)

And again, thanks......
